matrix:
  include:
  - os: linux
    language: python
    python: "3.6"
    compiler: gcc-5
    env: CC=gcc

  - os: linux
    language: python
    python: "3.5"
    compiler: gcc-5
    env: CC=gcc


sudo: false

cache: pip

install:
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\"" # show python version
  - pip install -r requirements.txt
  - pip install pytest
script:
  - python setup.py build_ext --inplace
  - pytest -v -s
